title:              Dhvani Katkoria
email:              dhvaniskatkoria@gmail.com
subtitle:           Dhvani - The Resonance Within
description:        A Journey of Self-Discovery
author:             Dhvani
baseurl:            ""
url:                "https://dhvani-katkoria.github.io"

# Social Profiles
twitter_username:   SBootstrap
github_username:    StartBootstrap
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username: Dhvani Katkoria
googlescholar_username: Dhvani Katkoria
dblp_username: Dhvani Katkoria

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

collections:
  publications:
    output: true
    permalink: /publications/:path/
    
# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
